languageCode = 'en-uk'
title = 'Invest in the UK, Invest in Lincolnshire'
baseURL = 'https://investlincolnshire.co.uk/'

[params]
  contactdomain = 'https://investlincolnshire.co.uk/'
  image_q_f = 'q_auto,f_auto/'
  imagedomain = 'https://res.cloudinary.com/lincs/image/upload/'

[module]
  [[module.imports]]
    path = "github.com/crescolincs/lincs-theme"

  #[[module.imports.mounts]]
  #  source = 'archetypes'
  #  target = 'archetypes'
  #  source = 'assets'
  #  target = 'assets'    
  #  source = 'data'
  #  target = 'data'
  #  source = 'layouts'
  #  target = 'layouts'
  #  source = 'static/css'
  #  target = 'static/css'
  #  source = 'static/functions'
  #  target = 'static/functions'  
  #  source = 'static/js'
  #  target = 'static/js'
  #  source = 'static/webfonts'
  #  target = 'static/webfonts'    
#Update hugo modules (in our case the theme)$> hugo mod get -u
