baseURL = 'http://investlincolnshire.co.uk/'
languageCode = 'en-uk'
title = 'Invest in the UK, Invest in Lincolnshire'


[module]
  [[module.imports]]
    path = "github.com/crescolincs/lincs-theme"

