
languageCode = 'en-uk'
title = 'Invest in the UK, Invest in Lincolnshire'

[params]
  contactdomain = 'https://investlincolnshire.co.uk/'
  image_q_f = 'q_auto,f_auto/'
  imagedomain = 'https://res.cloudinary.com/lincs/image/upload/'

[module]
  [[module.imports]]
    path = "github.com/crescolincs/lincs-theme"

[[module.imports.mounts]]
    source = 'static/functions/processform'
    target = 'static/functions/shakeyform'

#Update hugo modules (in our case the theme)$> hugo mod get -u
