baseURL = 'https://investlincolnshire.co.uk/'

languageCode = 'en-uk'
title = 'Invest in the UK, Invest in Lincolnshire'

[params]
  contactdomain = 'https://investlincolnshire.co.uk/'
  imagedomain = 'https://res.cloudinary.com/lincs/image/upload/q_auto,f_auto/'

[module]
  [[module.imports]]
    path = "github.com/crescolincs/lincs-theme"

#Update hugo modules (in our case the theme)$> hugo mod get -u
